_base_ = [
    "mmdet::_base_/models/faster-rcnn_r50_fpn.py",
    "mmdet::_base_/datasets/coco_detection.py",
    "mmdet::_base_/default_runtime.py",
]

# Toy COCO dataset generated by: `python mmdet_diffusers/tools/make_toy_coco.py`
data_root = "datasets/toy_coco/"
metainfo = dict(classes=("person",), palette=[(220, 20, 60)])

train_dataloader = dict(
    batch_size=1,
    num_workers=0,
    persistent_workers=False,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file="annotations/instances_train.json",
        data_prefix=dict(img="images/"),
        filter_cfg=dict(filter_empty_gt=False),
    ),
)
val_dataloader = dict(
    batch_size=1,
    num_workers=0,
    persistent_workers=False,
    dataset=dict(
        data_root=data_root,
        metainfo=metainfo,
        ann_file="annotations/instances_val.json",
        data_prefix=dict(img="images/"),
        test_mode=True,
    ),
)
test_dataloader = val_dataloader

val_evaluator = dict(type="CocoMetric", ann_file=data_root + "annotations/instances_val.json", metric="bbox")
test_evaluator = val_evaluator

# 1-class detection head.
model = dict(
    backbone=dict(init_cfg=None),
    roi_head=dict(bbox_head=dict(num_classes=1)),
)

# Minimal 1-epoch schedule for smoke.
optim_wrapper = dict(
    optimizer=dict(type="SGD", lr=0.002, momentum=0.9, weight_decay=0.0001),
)
param_scheduler = [
    dict(type="LinearLR", start_factor=0.001, by_epoch=False, begin=0, end=10),
    dict(type="MultiStepLR", by_epoch=True, begin=0, end=1, milestones=[1], gamma=0.1),
]

train_cfg = dict(type="EpochBasedTrainLoop", max_epochs=1, val_interval=1)
val_cfg = dict(type="ValLoop")
test_cfg = dict(type="TestLoop")

default_hooks = dict(logger=dict(interval=1), checkpoint=dict(interval=1))
